### ISSUE TITLE
[Feature] Auto update

### ISSUE THREAD

**Issue by krtschmr** [transeos/ethos_monitor#2]
miner.py could do a self-update via `wget https://raw.githubusercontent.com/transeos/ethos_monitor/master/miner.py` or git.clone, then self-starting.

how about that?

**Comment by transeos** [comment]
Well this is a very small program with very specific purpose. Hence, I never thought that auto-update is required.

**Comment by transeos** [comment]
You can add following line in crontab (command:"crontab -e") for auto-update.

@daily cd <script directory>; git pull
